# Generated by Django 5.0.7 on 2024-08-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=40)),
                ('confirmation_code', models.CharField(max_length=60)),
            ],
        ),
    ]
