# Generated by Django 5.0.7 on 2024-07-31 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('d_o_b', models.DateField()),
                ('phone_number', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=15)),
                ('otp', models.CharField(blank=True, max_length=7)),
                ('otp_max_try', models.CharField(max_length=2)),
                ('otp_out', models.DateTimeField()),
                ('otp_expiry', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('date_joined', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=400)),
                ('phone_number', models.CharField(max_length=16)),
                ('website_url', models.CharField(blank=True, max_length=1000)),
                ('office', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
