# Generated by Django 5.0.7 on 2024-08-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_out',
            field=models.DateTimeField(null=True),
        ),
    ]
