# Generated by Django 5.0.7 on 2024-08-04 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 10, 37, 58, 796010, tzinfo=datetime.timezone.utc)),
        ),
    ]
